<?php
/**
 * NG_Customer extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       NG
 * @package        NG_Customer
 * @copyright      Copyright (c) 2014
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */?>

<div class = "dashboard">
    <?php echo $this->getMessagesBlock()->getGroupedHtml()
    ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?php echo $this->__('My Custom Link Page') ?></h2>
        </div>
    </div>
</div>